/**
 * Dataset de países ISO 3166-1 para soporte multi-país en Sellio.
 * Orden: CO, MX, BR, US, ES primero; el resto alfabético por nameEs.
 * Indicativos E.164 validados contra libphonenumber-js y el estándar ITU-T E.164.
 * Nota: países NANP (Norteamérica + Caribe) comparten el indicativo "1".
 */

export type Country = {
  iso2: string;
  dialCode: string;
  nameEs: string;
  nameEn: string;
  namePt: string;
  flag: string;
  defaultTimezone: string;
};

export const COUNTRIES: Country[] = [
  // ── Prioridad LATAM + España ──────────────────────────────────────────────
  { iso2: 'CO', dialCode: '57',  nameEs: 'Colombia',              nameEn: 'Colombia',                  namePt: 'Colômbia',               flag: '🇨🇴', defaultTimezone: 'America/Bogota' },
  { iso2: 'MX', dialCode: '52',  nameEs: 'México',                nameEn: 'Mexico',                    namePt: 'México',                 flag: '🇲🇽', defaultTimezone: 'America/Mexico_City' },
  { iso2: 'BR', dialCode: '55',  nameEs: 'Brasil',                nameEn: 'Brazil',                    namePt: 'Brasil',                 flag: '🇧🇷', defaultTimezone: 'America/Sao_Paulo' },
  { iso2: 'US', dialCode: '1',   nameEs: 'Estados Unidos',        nameEn: 'United States',             namePt: 'Estados Unidos',         flag: '🇺🇸', defaultTimezone: 'America/New_York' },
  { iso2: 'ES', dialCode: '34',  nameEs: 'España',                nameEn: 'Spain',                     namePt: 'Espanha',                flag: '🇪🇸', defaultTimezone: 'Europe/Madrid' },

  // ── Resto alfabético por nameEs ───────────────────────────────────────────
  { iso2: 'AF', dialCode: '93',  nameEs: 'Afganistán',            nameEn: 'Afghanistan',               namePt: 'Afeganistão',            flag: '🇦🇫', defaultTimezone: 'Asia/Kabul' },
  { iso2: 'AL', dialCode: '355', nameEs: 'Albania',               nameEn: 'Albania',                   namePt: 'Albânia',                flag: '🇦🇱', defaultTimezone: 'Europe/Tirane' },
  { iso2: 'DE', dialCode: '49',  nameEs: 'Alemania',              nameEn: 'Germany',                   namePt: 'Alemanha',               flag: '🇩🇪', defaultTimezone: 'Europe/Berlin' },
  { iso2: 'AD', dialCode: '376', nameEs: 'Andorra',               nameEn: 'Andorra',                   namePt: 'Andorra',                flag: '🇦🇩', defaultTimezone: 'Europe/Andorra' },
  { iso2: 'AO', dialCode: '244', nameEs: 'Angola',                nameEn: 'Angola',                    namePt: 'Angola',                 flag: '🇦🇴', defaultTimezone: 'Africa/Luanda' },
  { iso2: 'AG', dialCode: '1',   nameEs: 'Antigua y Barbuda',     nameEn: 'Antigua and Barbuda',       namePt: 'Antígua e Barbuda',      flag: '🇦🇬', defaultTimezone: 'America/Antigua' },
  { iso2: 'SA', dialCode: '966', nameEs: 'Arabia Saudita',        nameEn: 'Saudi Arabia',              namePt: 'Arábia Saudita',         flag: '🇸🇦', defaultTimezone: 'Asia/Riyadh' },
  { iso2: 'DZ', dialCode: '213', nameEs: 'Argelia',               nameEn: 'Algeria',                   namePt: 'Argélia',                flag: '🇩🇿', defaultTimezone: 'Africa/Algiers' },
  { iso2: 'AR', dialCode: '54',  nameEs: 'Argentina',             nameEn: 'Argentina',                 namePt: 'Argentina',              flag: '🇦🇷', defaultTimezone: 'America/Argentina/Buenos_Aires' },
  { iso2: 'AM', dialCode: '374', nameEs: 'Armenia',               nameEn: 'Armenia',                   namePt: 'Armênia',                flag: '🇦🇲', defaultTimezone: 'Asia/Yerevan' },
  { iso2: 'AU', dialCode: '61',  nameEs: 'Australia',             nameEn: 'Australia',                 namePt: 'Austrália',              flag: '🇦🇺', defaultTimezone: 'Australia/Sydney' },
  { iso2: 'AT', dialCode: '43',  nameEs: 'Austria',               nameEn: 'Austria',                   namePt: 'Áustria',                flag: '🇦🇹', defaultTimezone: 'Europe/Vienna' },
  { iso2: 'AZ', dialCode: '994', nameEs: 'Azerbaiyán',            nameEn: 'Azerbaijan',                namePt: 'Azerbaijão',             flag: '🇦🇿', defaultTimezone: 'Asia/Baku' },
  { iso2: 'BS', dialCode: '1',   nameEs: 'Bahamas',               nameEn: 'Bahamas',                   namePt: 'Bahamas',                flag: '🇧🇸', defaultTimezone: 'America/Nassau' },
  { iso2: 'BH', dialCode: '973', nameEs: 'Baréin',                nameEn: 'Bahrain',                   namePt: 'Bahrein',                flag: '🇧🇭', defaultTimezone: 'Asia/Bahrain' },
  { iso2: 'BD', dialCode: '880', nameEs: 'Bangladés',             nameEn: 'Bangladesh',                namePt: 'Bangladesh',             flag: '🇧🇩', defaultTimezone: 'Asia/Dhaka' },
  { iso2: 'BB', dialCode: '1',   nameEs: 'Barbados',              nameEn: 'Barbados',                  namePt: 'Barbados',               flag: '🇧🇧', defaultTimezone: 'America/Barbados' },
  { iso2: 'BE', dialCode: '32',  nameEs: 'Bélgica',               nameEn: 'Belgium',                   namePt: 'Bélgica',                flag: '🇧🇪', defaultTimezone: 'Europe/Brussels' },
  { iso2: 'BZ', dialCode: '501', nameEs: 'Belice',                nameEn: 'Belize',                    namePt: 'Belize',                 flag: '🇧🇿', defaultTimezone: 'America/Belize' },
  { iso2: 'BJ', dialCode: '229', nameEs: 'Benín',                 nameEn: 'Benin',                     namePt: 'Benin',                  flag: '🇧🇯', defaultTimezone: 'Africa/Porto-Novo' },
  { iso2: 'BY', dialCode: '375', nameEs: 'Bielorrusia',           nameEn: 'Belarus',                   namePt: 'Bielorrússia',           flag: '🇧🇾', defaultTimezone: 'Europe/Minsk' },
  { iso2: 'MM', dialCode: '95',  nameEs: 'Birmania (Myanmar)',    nameEn: 'Myanmar',                   namePt: 'Mianmar (Birmânia)',      flag: '🇲🇲', defaultTimezone: 'Asia/Rangoon' },
  { iso2: 'BO', dialCode: '591', nameEs: 'Bolivia',               nameEn: 'Bolivia',                   namePt: 'Bolívia',                flag: '🇧🇴', defaultTimezone: 'America/La_Paz' },
  { iso2: 'BA', dialCode: '387', nameEs: 'Bosnia y Herzegovina',  nameEn: 'Bosnia and Herzegovina',    namePt: 'Bósnia e Herzegovina',   flag: '🇧🇦', defaultTimezone: 'Europe/Sarajevo' },
  { iso2: 'BW', dialCode: '267', nameEs: 'Botsuana',              nameEn: 'Botswana',                  namePt: 'Botsuana',               flag: '🇧🇼', defaultTimezone: 'Africa/Gaborone' },
  { iso2: 'BN', dialCode: '673', nameEs: 'Brunéi',                nameEn: 'Brunei',                    namePt: 'Brunei',                 flag: '🇧🇳', defaultTimezone: 'Asia/Brunei' },
  { iso2: 'BG', dialCode: '359', nameEs: 'Bulgaria',              nameEn: 'Bulgaria',                  namePt: 'Bulgária',               flag: '🇧🇬', defaultTimezone: 'Europe/Sofia' },
  { iso2: 'BF', dialCode: '226', nameEs: 'Burkina Faso',          nameEn: 'Burkina Faso',              namePt: 'Burkina Fasso',          flag: '🇧🇫', defaultTimezone: 'Africa/Ouagadougou' },
  { iso2: 'BI', dialCode: '257', nameEs: 'Burundi',               nameEn: 'Burundi',                   namePt: 'Burundi',                flag: '🇧🇮', defaultTimezone: 'Africa/Bujumbura' },
  { iso2: 'BT', dialCode: '975', nameEs: 'Bután',                 nameEn: 'Bhutan',                    namePt: 'Butão',                  flag: '🇧🇹', defaultTimezone: 'Asia/Thimphu' },
  { iso2: 'CV', dialCode: '238', nameEs: 'Cabo Verde',            nameEn: 'Cape Verde',                namePt: 'Cabo Verde',             flag: '🇨🇻', defaultTimezone: 'Atlantic/Cape_Verde' },
  { iso2: 'KH', dialCode: '855', nameEs: 'Camboya',               nameEn: 'Cambodia',                  namePt: 'Camboja',                flag: '🇰🇭', defaultTimezone: 'Asia/Phnom_Penh' },
  { iso2: 'CM', dialCode: '237', nameEs: 'Camerún',               nameEn: 'Cameroon',                  namePt: 'Camarões',               flag: '🇨🇲', defaultTimezone: 'Africa/Douala' },
  { iso2: 'CA', dialCode: '1',   nameEs: 'Canadá',                nameEn: 'Canada',                    namePt: 'Canadá',                 flag: '🇨🇦', defaultTimezone: 'America/Toronto' },
  { iso2: 'QA', dialCode: '974', nameEs: 'Catar',                 nameEn: 'Qatar',                     namePt: 'Catar',                  flag: '🇶🇦', defaultTimezone: 'Asia/Qatar' },
  { iso2: 'TD', dialCode: '235', nameEs: 'Chad',                  nameEn: 'Chad',                      namePt: 'Chade',                  flag: '🇹🇩', defaultTimezone: 'Africa/Ndjamena' },
  { iso2: 'CZ', dialCode: '420', nameEs: 'Chequia',               nameEn: 'Czech Republic',            namePt: 'Chéquia',                flag: '🇨🇿', defaultTimezone: 'Europe/Prague' },
  { iso2: 'CL', dialCode: '56',  nameEs: 'Chile',                 nameEn: 'Chile',                     namePt: 'Chile',                  flag: '🇨🇱', defaultTimezone: 'America/Santiago' },
  { iso2: 'CN', dialCode: '86',  nameEs: 'China',                 nameEn: 'China',                     namePt: 'China',                  flag: '🇨🇳', defaultTimezone: 'Asia/Shanghai' },
  { iso2: 'CY', dialCode: '357', nameEs: 'Chipre',                nameEn: 'Cyprus',                    namePt: 'Chipre',                 flag: '🇨🇾', defaultTimezone: 'Asia/Nicosia' },
  { iso2: 'VA', dialCode: '39',  nameEs: 'Ciudad del Vaticano',   nameEn: 'Vatican City',              namePt: 'Cidade do Vaticano',     flag: '🇻🇦', defaultTimezone: 'Europe/Vatican' },
  { iso2: 'KM', dialCode: '269', nameEs: 'Comoras',               nameEn: 'Comoros',                   namePt: 'Comores',                flag: '🇰🇲', defaultTimezone: 'Indian/Comoro' },
  { iso2: 'CG', dialCode: '242', nameEs: 'Congo',                 nameEn: 'Republic of the Congo',     namePt: 'Congo',                  flag: '🇨🇬', defaultTimezone: 'Africa/Brazzaville' },
  { iso2: 'CD', dialCode: '243', nameEs: 'Congo (RDC)',            nameEn: 'DR Congo',                  namePt: 'Congo (RDC)',            flag: '🇨🇩', defaultTimezone: 'Africa/Kinshasa' },
  { iso2: 'KP', dialCode: '850', nameEs: 'Corea del Norte',       nameEn: 'North Korea',               namePt: 'Coreia do Norte',        flag: '🇰🇵', defaultTimezone: 'Asia/Pyongyang' },
  { iso2: 'KR', dialCode: '82',  nameEs: 'Corea del Sur',         nameEn: 'South Korea',               namePt: 'Coreia do Sul',          flag: '🇰🇷', defaultTimezone: 'Asia/Seoul' },
  { iso2: 'CI', dialCode: '225', nameEs: 'Costa de Marfil',       nameEn: 'Ivory Coast',               namePt: 'Costa do Marfim',        flag: '🇨🇮', defaultTimezone: 'Africa/Abidjan' },
  { iso2: 'CR', dialCode: '506', nameEs: 'Costa Rica',            nameEn: 'Costa Rica',                namePt: 'Costa Rica',             flag: '🇨🇷', defaultTimezone: 'America/Costa_Rica' },
  { iso2: 'HR', dialCode: '385', nameEs: 'Croacia',               nameEn: 'Croatia',                   namePt: 'Croácia',                flag: '🇭🇷', defaultTimezone: 'Europe/Zagreb' },
  { iso2: 'CU', dialCode: '53',  nameEs: 'Cuba',                  nameEn: 'Cuba',                      namePt: 'Cuba',                   flag: '🇨🇺', defaultTimezone: 'America/Havana' },
  { iso2: 'DK', dialCode: '45',  nameEs: 'Dinamarca',             nameEn: 'Denmark',                   namePt: 'Dinamarca',              flag: '🇩🇰', defaultTimezone: 'Europe/Copenhagen' },
  { iso2: 'DM', dialCode: '1',   nameEs: 'Dominica',              nameEn: 'Dominica',                  namePt: 'Dominica',               flag: '🇩🇲', defaultTimezone: 'America/Dominica' },
  { iso2: 'EC', dialCode: '593', nameEs: 'Ecuador',               nameEn: 'Ecuador',                   namePt: 'Equador',                flag: '🇪🇨', defaultTimezone: 'America/Guayaquil' },
  { iso2: 'EG', dialCode: '20',  nameEs: 'Egipto',                nameEn: 'Egypt',                     namePt: 'Egito',                  flag: '🇪🇬', defaultTimezone: 'Africa/Cairo' },
  { iso2: 'SV', dialCode: '503', nameEs: 'El Salvador',           nameEn: 'El Salvador',               namePt: 'El Salvador',            flag: '🇸🇻', defaultTimezone: 'America/El_Salvador' },
  { iso2: 'AE', dialCode: '971', nameEs: 'Emiratos Árabes Unidos',nameEn: 'United Arab Emirates',      namePt: 'Emirados Árabes Unidos', flag: '🇦🇪', defaultTimezone: 'Asia/Dubai' },
  { iso2: 'ER', dialCode: '291', nameEs: 'Eritrea',               nameEn: 'Eritrea',                   namePt: 'Eritreia',               flag: '🇪🇷', defaultTimezone: 'Africa/Asmara' },
  { iso2: 'SK', dialCode: '421', nameEs: 'Eslovaquia',            nameEn: 'Slovakia',                  namePt: 'Eslováquia',             flag: '🇸🇰', defaultTimezone: 'Europe/Bratislava' },
  { iso2: 'SI', dialCode: '386', nameEs: 'Eslovenia',             nameEn: 'Slovenia',                  namePt: 'Eslovênia',              flag: '🇸🇮', defaultTimezone: 'Europe/Ljubljana' },
  { iso2: 'EE', dialCode: '372', nameEs: 'Estonia',               nameEn: 'Estonia',                   namePt: 'Estônia',                flag: '🇪🇪', defaultTimezone: 'Europe/Tallinn' },
  { iso2: 'SZ', dialCode: '268', nameEs: 'Esuatini',              nameEn: 'Eswatini',                  namePt: 'Eswatini',               flag: '🇸🇿', defaultTimezone: 'Africa/Mbabane' },
  { iso2: 'ET', dialCode: '251', nameEs: 'Etiopía',               nameEn: 'Ethiopia',                  namePt: 'Etiópia',                flag: '🇪🇹', defaultTimezone: 'Africa/Addis_Ababa' },
  { iso2: 'PH', dialCode: '63',  nameEs: 'Filipinas',             nameEn: 'Philippines',               namePt: 'Filipinas',              flag: '🇵🇭', defaultTimezone: 'Asia/Manila' },
  { iso2: 'FI', dialCode: '358', nameEs: 'Finlandia',             nameEn: 'Finland',                   namePt: 'Finlândia',              flag: '🇫🇮', defaultTimezone: 'Europe/Helsinki' },
  { iso2: 'FJ', dialCode: '679', nameEs: 'Fiyi',                  nameEn: 'Fiji',                      namePt: 'Fiji',                   flag: '🇫🇯', defaultTimezone: 'Pacific/Fiji' },
  { iso2: 'FR', dialCode: '33',  nameEs: 'Francia',               nameEn: 'France',                    namePt: 'França',                 flag: '🇫🇷', defaultTimezone: 'Europe/Paris' },
  { iso2: 'GA', dialCode: '241', nameEs: 'Gabón',                 nameEn: 'Gabon',                     namePt: 'Gabão',                  flag: '🇬🇦', defaultTimezone: 'Africa/Libreville' },
  { iso2: 'GM', dialCode: '220', nameEs: 'Gambia',                nameEn: 'Gambia',                    namePt: 'Gâmbia',                 flag: '🇬🇲', defaultTimezone: 'Africa/Banjul' },
  { iso2: 'GE', dialCode: '995', nameEs: 'Georgia',               nameEn: 'Georgia',                   namePt: 'Geórgia',                flag: '🇬🇪', defaultTimezone: 'Asia/Tbilisi' },
  { iso2: 'GH', dialCode: '233', nameEs: 'Ghana',                 nameEn: 'Ghana',                     namePt: 'Gana',                   flag: '🇬🇭', defaultTimezone: 'Africa/Accra' },
  { iso2: 'GD', dialCode: '1',   nameEs: 'Granada',               nameEn: 'Grenada',                   namePt: 'Granada',                flag: '🇬🇩', defaultTimezone: 'America/Grenada' },
  { iso2: 'GB', dialCode: '44',  nameEs: 'Gran Bretaña (RU)',     nameEn: 'United Kingdom',            namePt: 'Reino Unido',            flag: '🇬🇧', defaultTimezone: 'Europe/London' },
  { iso2: 'GR', dialCode: '30',  nameEs: 'Grecia',                nameEn: 'Greece',                    namePt: 'Grécia',                 flag: '🇬🇷', defaultTimezone: 'Europe/Athens' },
  { iso2: 'GT', dialCode: '502', nameEs: 'Guatemala',             nameEn: 'Guatemala',                 namePt: 'Guatemala',              flag: '🇬🇹', defaultTimezone: 'America/Guatemala' },
  { iso2: 'GN', dialCode: '224', nameEs: 'Guinea',                nameEn: 'Guinea',                    namePt: 'Guiné',                  flag: '🇬🇳', defaultTimezone: 'Africa/Conakry' },
  { iso2: 'GQ', dialCode: '240', nameEs: 'Guinea Ecuatorial',     nameEn: 'Equatorial Guinea',         namePt: 'Guiné Equatorial',       flag: '🇬🇶', defaultTimezone: 'Africa/Malabo' },
  { iso2: 'GW', dialCode: '245', nameEs: 'Guinea-Bisáu',          nameEn: 'Guinea-Bissau',             namePt: 'Guiné-Bissau',           flag: '🇬🇼', defaultTimezone: 'Africa/Bissau' },
  { iso2: 'GY', dialCode: '592', nameEs: 'Guyana',                nameEn: 'Guyana',                    namePt: 'Guiana',                 flag: '🇬🇾', defaultTimezone: 'America/Guyana' },
  { iso2: 'HT', dialCode: '509', nameEs: 'Haití',                 nameEn: 'Haiti',                     namePt: 'Haiti',                  flag: '🇭🇹', defaultTimezone: 'America/Port-au-Prince' },
  { iso2: 'HN', dialCode: '504', nameEs: 'Honduras',              nameEn: 'Honduras',                  namePt: 'Honduras',               flag: '🇭🇳', defaultTimezone: 'America/Tegucigalpa' },
  { iso2: 'HU', dialCode: '36',  nameEs: 'Hungría',               nameEn: 'Hungary',                   namePt: 'Hungria',                flag: '🇭🇺', defaultTimezone: 'Europe/Budapest' },
  { iso2: 'IN', dialCode: '91',  nameEs: 'India',                 nameEn: 'India',                     namePt: 'Índia',                  flag: '🇮🇳', defaultTimezone: 'Asia/Kolkata' },
  { iso2: 'ID', dialCode: '62',  nameEs: 'Indonesia',             nameEn: 'Indonesia',                 namePt: 'Indonésia',              flag: '🇮🇩', defaultTimezone: 'Asia/Jakarta' },
  { iso2: 'IQ', dialCode: '964', nameEs: 'Irak',                  nameEn: 'Iraq',                      namePt: 'Iraque',                 flag: '🇮🇶', defaultTimezone: 'Asia/Baghdad' },
  { iso2: 'IR', dialCode: '98',  nameEs: 'Irán',                  nameEn: 'Iran',                      namePt: 'Irã',                    flag: '🇮🇷', defaultTimezone: 'Asia/Tehran' },
  { iso2: 'IE', dialCode: '353', nameEs: 'Irlanda',               nameEn: 'Ireland',                   namePt: 'Irlanda',                flag: '🇮🇪', defaultTimezone: 'Europe/Dublin' },
  { iso2: 'IS', dialCode: '354', nameEs: 'Islandia',              nameEn: 'Iceland',                   namePt: 'Islândia',               flag: '🇮🇸', defaultTimezone: 'Atlantic/Reykjavik' },
  { iso2: 'MH', dialCode: '692', nameEs: 'Islas Marshall',        nameEn: 'Marshall Islands',          namePt: 'Ilhas Marshall',         flag: '🇲🇭', defaultTimezone: 'Pacific/Majuro' },
  { iso2: 'SB', dialCode: '677', nameEs: 'Islas Salomón',         nameEn: 'Solomon Islands',           namePt: 'Ilhas Salomão',          flag: '🇸🇧', defaultTimezone: 'Pacific/Guadalcanal' },
  { iso2: 'IL', dialCode: '972', nameEs: 'Israel',                nameEn: 'Israel',                    namePt: 'Israel',                 flag: '🇮🇱', defaultTimezone: 'Asia/Jerusalem' },
  { iso2: 'IT', dialCode: '39',  nameEs: 'Italia',                nameEn: 'Italy',                     namePt: 'Itália',                 flag: '🇮🇹', defaultTimezone: 'Europe/Rome' },
  { iso2: 'JM', dialCode: '1',   nameEs: 'Jamaica',               nameEn: 'Jamaica',                   namePt: 'Jamaica',                flag: '🇯🇲', defaultTimezone: 'America/Jamaica' },
  { iso2: 'JP', dialCode: '81',  nameEs: 'Japón',                 nameEn: 'Japan',                     namePt: 'Japão',                  flag: '🇯🇵', defaultTimezone: 'Asia/Tokyo' },
  { iso2: 'JO', dialCode: '962', nameEs: 'Jordania',              nameEn: 'Jordan',                    namePt: 'Jordânia',               flag: '🇯🇴', defaultTimezone: 'Asia/Amman' },
  { iso2: 'KZ', dialCode: '7',   nameEs: 'Kazajistán',            nameEn: 'Kazakhstan',                namePt: 'Cazaquistão',            flag: '🇰🇿', defaultTimezone: 'Asia/Almaty' },
  { iso2: 'KE', dialCode: '254', nameEs: 'Kenia',                 nameEn: 'Kenya',                     namePt: 'Quênia',                 flag: '🇰🇪', defaultTimezone: 'Africa/Nairobi' },
  { iso2: 'KG', dialCode: '996', nameEs: 'Kirguistán',            nameEn: 'Kyrgyzstan',                namePt: 'Quirguistão',            flag: '🇰🇬', defaultTimezone: 'Asia/Bishkek' },
  { iso2: 'KI', dialCode: '686', nameEs: 'Kiribati',              nameEn: 'Kiribati',                  namePt: 'Quiribati',              flag: '🇰🇮', defaultTimezone: 'Pacific/Tarawa' },
  { iso2: 'KW', dialCode: '965', nameEs: 'Kuwait',                nameEn: 'Kuwait',                    namePt: 'Kuwait',                 flag: '🇰🇼', defaultTimezone: 'Asia/Kuwait' },
  { iso2: 'LA', dialCode: '856', nameEs: 'Laos',                  nameEn: 'Laos',                      namePt: 'Laos',                   flag: '🇱🇦', defaultTimezone: 'Asia/Vientiane' },
  { iso2: 'LS', dialCode: '266', nameEs: 'Lesoto',                nameEn: 'Lesotho',                   namePt: 'Lesoto',                 flag: '🇱🇸', defaultTimezone: 'Africa/Maseru' },
  { iso2: 'LV', dialCode: '371', nameEs: 'Letonia',               nameEn: 'Latvia',                    namePt: 'Letônia',                flag: '🇱🇻', defaultTimezone: 'Europe/Riga' },
  { iso2: 'LB', dialCode: '961', nameEs: 'Líbano',                nameEn: 'Lebanon',                   namePt: 'Líbano',                 flag: '🇱🇧', defaultTimezone: 'Asia/Beirut' },
  { iso2: 'LR', dialCode: '231', nameEs: 'Liberia',               nameEn: 'Liberia',                   namePt: 'Libéria',                flag: '🇱🇷', defaultTimezone: 'Africa/Monrovia' },
  { iso2: 'LY', dialCode: '218', nameEs: 'Libia',                 nameEn: 'Libya',                     namePt: 'Líbia',                  flag: '🇱🇾', defaultTimezone: 'Africa/Tripoli' },
  { iso2: 'LI', dialCode: '423', nameEs: 'Liechtenstein',         nameEn: 'Liechtenstein',             namePt: 'Liechtenstein',          flag: '🇱🇮', defaultTimezone: 'Europe/Vaduz' },
  { iso2: 'LT', dialCode: '370', nameEs: 'Lituania',              nameEn: 'Lithuania',                 namePt: 'Lituânia',               flag: '🇱🇹', defaultTimezone: 'Europe/Vilnius' },
  { iso2: 'LU', dialCode: '352', nameEs: 'Luxemburgo',            nameEn: 'Luxembourg',                namePt: 'Luxemburgo',             flag: '🇱🇺', defaultTimezone: 'Europe/Luxembourg' },
  { iso2: 'MK', dialCode: '389', nameEs: 'Macedonia del Norte',   nameEn: 'North Macedonia',           namePt: 'Macedônia do Norte',     flag: '🇲🇰', defaultTimezone: 'Europe/Skopje' },
  { iso2: 'MG', dialCode: '261', nameEs: 'Madagascar',            nameEn: 'Madagascar',                namePt: 'Madagáscar',             flag: '🇲🇬', defaultTimezone: 'Indian/Antananarivo' },
  { iso2: 'MY', dialCode: '60',  nameEs: 'Malasia',               nameEn: 'Malaysia',                  namePt: 'Malásia',                flag: '🇲🇾', defaultTimezone: 'Asia/Kuala_Lumpur' },
  { iso2: 'MW', dialCode: '265', nameEs: 'Malaui',                nameEn: 'Malawi',                    namePt: 'Maláui',                 flag: '🇲🇼', defaultTimezone: 'Africa/Blantyre' },
  { iso2: 'MV', dialCode: '960', nameEs: 'Maldivas',              nameEn: 'Maldives',                  namePt: 'Maldivas',               flag: '🇲🇻', defaultTimezone: 'Indian/Maldives' },
  { iso2: 'ML', dialCode: '223', nameEs: 'Malí',                  nameEn: 'Mali',                      namePt: 'Mali',                   flag: '🇲🇱', defaultTimezone: 'Africa/Bamako' },
  { iso2: 'MT', dialCode: '356', nameEs: 'Malta',                 nameEn: 'Malta',                     namePt: 'Malta',                  flag: '🇲🇹', defaultTimezone: 'Europe/Malta' },
  { iso2: 'MA', dialCode: '212', nameEs: 'Marruecos',             nameEn: 'Morocco',                   namePt: 'Marrocos',               flag: '🇲🇦', defaultTimezone: 'Africa/Casablanca' },
  { iso2: 'MU', dialCode: '230', nameEs: 'Mauricio',              nameEn: 'Mauritius',                 namePt: 'Maurício',               flag: '🇲🇺', defaultTimezone: 'Indian/Mauritius' },
  { iso2: 'MR', dialCode: '222', nameEs: 'Mauritania',            nameEn: 'Mauritania',                namePt: 'Mauritânia',             flag: '🇲🇷', defaultTimezone: 'Africa/Nouakchott' },
  { iso2: 'FM', dialCode: '691', nameEs: 'Micronesia',            nameEn: 'Micronesia',                namePt: 'Micronésia',             flag: '🇫🇲', defaultTimezone: 'Pacific/Pohnpei' },
  { iso2: 'MD', dialCode: '373', nameEs: 'Moldavia',              nameEn: 'Moldova',                   namePt: 'Moldávia',               flag: '🇲🇩', defaultTimezone: 'Europe/Chisinau' },
  { iso2: 'MC', dialCode: '377', nameEs: 'Mónaco',                nameEn: 'Monaco',                    namePt: 'Mônaco',                 flag: '🇲🇨', defaultTimezone: 'Europe/Monaco' },
  { iso2: 'MN', dialCode: '976', nameEs: 'Mongolia',              nameEn: 'Mongolia',                  namePt: 'Mongólia',               flag: '🇲🇳', defaultTimezone: 'Asia/Ulaanbaatar' },
  { iso2: 'ME', dialCode: '382', nameEs: 'Montenegro',            nameEn: 'Montenegro',                namePt: 'Montenegro',             flag: '🇲🇪', defaultTimezone: 'Europe/Podgorica' },
  { iso2: 'MZ', dialCode: '258', nameEs: 'Mozambique',            nameEn: 'Mozambique',                namePt: 'Moçambique',             flag: '🇲🇿', defaultTimezone: 'Africa/Maputo' },
  { iso2: 'NA', dialCode: '264', nameEs: 'Namibia',               nameEn: 'Namibia',                   namePt: 'Namíbia',                flag: '🇳🇦', defaultTimezone: 'Africa/Windhoek' },
  { iso2: 'NR', dialCode: '674', nameEs: 'Nauru',                 nameEn: 'Nauru',                     namePt: 'Nauru',                  flag: '🇳🇷', defaultTimezone: 'Pacific/Nauru' },
  { iso2: 'NP', dialCode: '977', nameEs: 'Nepal',                 nameEn: 'Nepal',                     namePt: 'Nepal',                  flag: '🇳🇵', defaultTimezone: 'Asia/Kathmandu' },
  { iso2: 'NI', dialCode: '505', nameEs: 'Nicaragua',             nameEn: 'Nicaragua',                 namePt: 'Nicarágua',              flag: '🇳🇮', defaultTimezone: 'America/Managua' },
  { iso2: 'NE', dialCode: '227', nameEs: 'Níger',                 nameEn: 'Niger',                     namePt: 'Níger',                  flag: '🇳🇪', defaultTimezone: 'Africa/Niamey' },
  { iso2: 'NG', dialCode: '234', nameEs: 'Nigeria',               nameEn: 'Nigeria',                   namePt: 'Nigéria',                flag: '🇳🇬', defaultTimezone: 'Africa/Lagos' },
  { iso2: 'NO', dialCode: '47',  nameEs: 'Noruega',               nameEn: 'Norway',                    namePt: 'Noruega',                flag: '🇳🇴', defaultTimezone: 'Europe/Oslo' },
  { iso2: 'NZ', dialCode: '64',  nameEs: 'Nueva Zelanda',         nameEn: 'New Zealand',               namePt: 'Nova Zelândia',          flag: '🇳🇿', defaultTimezone: 'Pacific/Auckland' },
  { iso2: 'OM', dialCode: '968', nameEs: 'Omán',                  nameEn: 'Oman',                      namePt: 'Omã',                    flag: '🇴🇲', defaultTimezone: 'Asia/Muscat' },
  { iso2: 'NL', dialCode: '31',  nameEs: 'Países Bajos',          nameEn: 'Netherlands',               namePt: 'Países Baixos',          flag: '🇳🇱', defaultTimezone: 'Europe/Amsterdam' },
  { iso2: 'PK', dialCode: '92',  nameEs: 'Pakistán',              nameEn: 'Pakistan',                  namePt: 'Paquistão',              flag: '🇵🇰', defaultTimezone: 'Asia/Karachi' },
  { iso2: 'PW', dialCode: '680', nameEs: 'Palaos',                nameEn: 'Palau',                     namePt: 'Palau',                  flag: '🇵🇼', defaultTimezone: 'Pacific/Palau' },
  { iso2: 'PA', dialCode: '507', nameEs: 'Panamá',                nameEn: 'Panama',                    namePt: 'Panamá',                 flag: '🇵🇦', defaultTimezone: 'America/Panama' },
  { iso2: 'PG', dialCode: '675', nameEs: 'Papúa Nueva Guinea',    nameEn: 'Papua New Guinea',          namePt: 'Papua-Nova Guiné',       flag: '🇵🇬', defaultTimezone: 'Pacific/Port_Moresby' },
  { iso2: 'PY', dialCode: '595', nameEs: 'Paraguay',              nameEn: 'Paraguay',                  namePt: 'Paraguai',               flag: '🇵🇾', defaultTimezone: 'America/Asuncion' },
  { iso2: 'PE', dialCode: '51',  nameEs: 'Perú',                  nameEn: 'Peru',                      namePt: 'Peru',                   flag: '🇵🇪', defaultTimezone: 'America/Lima' },
  { iso2: 'PL', dialCode: '48',  nameEs: 'Polonia',               nameEn: 'Poland',                    namePt: 'Polônia',                flag: '🇵🇱', defaultTimezone: 'Europe/Warsaw' },
  { iso2: 'PT', dialCode: '351', nameEs: 'Portugal',              nameEn: 'Portugal',                  namePt: 'Portugal',               flag: '🇵🇹', defaultTimezone: 'Europe/Lisbon' },
  { iso2: 'DO', dialCode: '1',   nameEs: 'República Dominicana',  nameEn: 'Dominican Republic',        namePt: 'República Dominicana',   flag: '🇩🇴', defaultTimezone: 'America/Santo_Domingo' },
  { iso2: 'RW', dialCode: '250', nameEs: 'Ruanda',                nameEn: 'Rwanda',                    namePt: 'Ruanda',                 flag: '🇷🇼', defaultTimezone: 'Africa/Kigali' },
  { iso2: 'RO', dialCode: '40',  nameEs: 'Rumanía',               nameEn: 'Romania',                   namePt: 'Romênia',                flag: '🇷🇴', defaultTimezone: 'Europe/Bucharest' },
  { iso2: 'RU', dialCode: '7',   nameEs: 'Rusia',                 nameEn: 'Russia',                    namePt: 'Rússia',                 flag: '🇷🇺', defaultTimezone: 'Europe/Moscow' },
  { iso2: 'WS', dialCode: '685', nameEs: 'Samoa',                 nameEn: 'Samoa',                     namePt: 'Samoa',                  flag: '🇼🇸', defaultTimezone: 'Pacific/Apia' },
  { iso2: 'KN', dialCode: '1',   nameEs: 'San Cristóbal y Nieves',nameEn: 'Saint Kitts and Nevis',     namePt: 'São Cristóvão e Nevis',  flag: '🇰🇳', defaultTimezone: 'America/St_Kitts' },
  { iso2: 'SM', dialCode: '378', nameEs: 'San Marino',            nameEn: 'San Marino',                namePt: 'San Marino',             flag: '🇸🇲', defaultTimezone: 'Europe/San_Marino' },
  { iso2: 'VC', dialCode: '1',   nameEs: 'San Vicente y las Granadinas', nameEn: 'Saint Vincent and the Grenadines', namePt: 'São Vicente e Granadinas', flag: '🇻🇨', defaultTimezone: 'America/St_Vincent' },
  { iso2: 'LC', dialCode: '1',   nameEs: 'Santa Lucía',           nameEn: 'Saint Lucia',               namePt: 'Santa Lúcia',            flag: '🇱🇨', defaultTimezone: 'America/St_Lucia' },
  { iso2: 'ST', dialCode: '239', nameEs: 'Santo Tomé y Príncipe', nameEn: 'Sao Tome and Principe',     namePt: 'São Tomé e Príncipe',    flag: '🇸🇹', defaultTimezone: 'Africa/Sao_Tome' },
  { iso2: 'SN', dialCode: '221', nameEs: 'Senegal',               nameEn: 'Senegal',                   namePt: 'Senegal',                flag: '🇸🇳', defaultTimezone: 'Africa/Dakar' },
  { iso2: 'RS', dialCode: '381', nameEs: 'Serbia',                nameEn: 'Serbia',                    namePt: 'Sérvia',                 flag: '🇷🇸', defaultTimezone: 'Europe/Belgrade' },
  { iso2: 'SC', dialCode: '248', nameEs: 'Seychelles',            nameEn: 'Seychelles',                namePt: 'Seicheles',              flag: '🇸🇨', defaultTimezone: 'Indian/Mahe' },
  { iso2: 'SL', dialCode: '232', nameEs: 'Sierra Leona',          nameEn: 'Sierra Leone',              namePt: 'Serra Leoa',             flag: '🇸🇱', defaultTimezone: 'Africa/Freetown' },
  { iso2: 'SG', dialCode: '65',  nameEs: 'Singapur',              nameEn: 'Singapore',                 namePt: 'Singapura',              flag: '🇸🇬', defaultTimezone: 'Asia/Singapore' },
  { iso2: 'SY', dialCode: '963', nameEs: 'Siria',                 nameEn: 'Syria',                     namePt: 'Síria',                  flag: '🇸🇾', defaultTimezone: 'Asia/Damascus' },
  { iso2: 'SO', dialCode: '252', nameEs: 'Somalia',               nameEn: 'Somalia',                   namePt: 'Somália',                flag: '🇸🇴', defaultTimezone: 'Africa/Mogadishu' },
  { iso2: 'LK', dialCode: '94',  nameEs: 'Sri Lanka',             nameEn: 'Sri Lanka',                 namePt: 'Sri Lanka',              flag: '🇱🇰', defaultTimezone: 'Asia/Colombo' },
  { iso2: 'ZA', dialCode: '27',  nameEs: 'Sudáfrica',             nameEn: 'South Africa',              namePt: 'África do Sul',          flag: '🇿🇦', defaultTimezone: 'Africa/Johannesburg' },
  { iso2: 'SD', dialCode: '249', nameEs: 'Sudán',                 nameEn: 'Sudan',                     namePt: 'Sudão',                  flag: '🇸🇩', defaultTimezone: 'Africa/Khartoum' },
  { iso2: 'SS', dialCode: '211', nameEs: 'Sudán del Sur',         nameEn: 'South Sudan',               namePt: 'Sudão do Sul',           flag: '🇸🇸', defaultTimezone: 'Africa/Juba' },
  { iso2: 'SE', dialCode: '46',  nameEs: 'Suecia',                nameEn: 'Sweden',                    namePt: 'Suécia',                 flag: '🇸🇪', defaultTimezone: 'Europe/Stockholm' },
  { iso2: 'CH', dialCode: '41',  nameEs: 'Suiza',                 nameEn: 'Switzerland',               namePt: 'Suíça',                  flag: '🇨🇭', defaultTimezone: 'Europe/Zurich' },
  { iso2: 'SR', dialCode: '597', nameEs: 'Surinam',               nameEn: 'Suriname',                  namePt: 'Suriname',               flag: '🇸🇷', defaultTimezone: 'America/Paramaribo' },
  { iso2: 'TH', dialCode: '66',  nameEs: 'Tailandia',             nameEn: 'Thailand',                  namePt: 'Tailândia',              flag: '🇹🇭', defaultTimezone: 'Asia/Bangkok' },
  { iso2: 'TW', dialCode: '886', nameEs: 'Taiwán',                nameEn: 'Taiwan',                    namePt: 'Taiwan',                 flag: '🇹🇼', defaultTimezone: 'Asia/Taipei' },
  { iso2: 'TZ', dialCode: '255', nameEs: 'Tanzania',              nameEn: 'Tanzania',                  namePt: 'Tanzânia',               flag: '🇹🇿', defaultTimezone: 'Africa/Dar_es_Salaam' },
  { iso2: 'TJ', dialCode: '992', nameEs: 'Tayikistán',            nameEn: 'Tajikistan',                namePt: 'Tajiquistão',            flag: '🇹🇯', defaultTimezone: 'Asia/Dushanbe' },
  { iso2: 'TL', dialCode: '670', nameEs: 'Timor-Leste',           nameEn: 'East Timor',                namePt: 'Timor-Leste',            flag: '🇹🇱', defaultTimezone: 'Asia/Dili' },
  { iso2: 'TG', dialCode: '228', nameEs: 'Togo',                  nameEn: 'Togo',                      namePt: 'Togo',                   flag: '🇹🇬', defaultTimezone: 'Africa/Lome' },
  { iso2: 'TO', dialCode: '676', nameEs: 'Tonga',                 nameEn: 'Tonga',                     namePt: 'Tonga',                  flag: '🇹🇴', defaultTimezone: 'Pacific/Tongatapu' },
  { iso2: 'TT', dialCode: '1',   nameEs: 'Trinidad y Tobago',     nameEn: 'Trinidad and Tobago',       namePt: 'Trinidad e Tobago',      flag: '🇹🇹', defaultTimezone: 'America/Port_of_Spain' },
  { iso2: 'TN', dialCode: '216', nameEs: 'Túnez',                 nameEn: 'Tunisia',                   namePt: 'Tunísia',                flag: '🇹🇳', defaultTimezone: 'Africa/Tunis' },
  { iso2: 'TM', dialCode: '993', nameEs: 'Turkmenistán',          nameEn: 'Turkmenistan',              namePt: 'Turquemenistão',         flag: '🇹🇲', defaultTimezone: 'Asia/Ashgabat' },
  { iso2: 'TR', dialCode: '90',  nameEs: 'Turquía',               nameEn: 'Turkey',                    namePt: 'Turquia',                flag: '🇹🇷', defaultTimezone: 'Europe/Istanbul' },
  { iso2: 'TV', dialCode: '688', nameEs: 'Tuvalu',                nameEn: 'Tuvalu',                    namePt: 'Tuvalu',                 flag: '🇹🇻', defaultTimezone: 'Pacific/Funafuti' },
  { iso2: 'UA', dialCode: '380', nameEs: 'Ucrania',               nameEn: 'Ukraine',                   namePt: 'Ucrânia',                flag: '🇺🇦', defaultTimezone: 'Europe/Kiev' },
  { iso2: 'UG', dialCode: '256', nameEs: 'Uganda',                nameEn: 'Uganda',                    namePt: 'Uganda',                 flag: '🇺🇬', defaultTimezone: 'Africa/Kampala' },
  { iso2: 'UY', dialCode: '598', nameEs: 'Uruguay',               nameEn: 'Uruguay',                   namePt: 'Uruguai',                flag: '🇺🇾', defaultTimezone: 'America/Montevideo' },
  { iso2: 'UZ', dialCode: '998', nameEs: 'Uzbekistán',            nameEn: 'Uzbekistan',                namePt: 'Uzbequistão',            flag: '🇺🇿', defaultTimezone: 'Asia/Tashkent' },
  { iso2: 'VU', dialCode: '678', nameEs: 'Vanuatu',               nameEn: 'Vanuatu',                   namePt: 'Vanuatu',                flag: '🇻🇺', defaultTimezone: 'Pacific/Efate' },
  { iso2: 'VE', dialCode: '58',  nameEs: 'Venezuela',             nameEn: 'Venezuela',                 namePt: 'Venezuela',              flag: '🇻🇪', defaultTimezone: 'America/Caracas' },
  { iso2: 'VN', dialCode: '84',  nameEs: 'Vietnam',               nameEn: 'Vietnam',                   namePt: 'Vietnã',                 flag: '🇻🇳', defaultTimezone: 'Asia/Ho_Chi_Minh' },
  { iso2: 'YE', dialCode: '967', nameEs: 'Yemen',                 nameEn: 'Yemen',                     namePt: 'Iêmen',                  flag: '🇾🇪', defaultTimezone: 'Asia/Aden' },
  { iso2: 'DJ', dialCode: '253', nameEs: 'Yibuti',                nameEn: 'Djibouti',                  namePt: 'Djibuti',                flag: '🇩🇯', defaultTimezone: 'Africa/Djibouti' },
  { iso2: 'ZM', dialCode: '260', nameEs: 'Zambia',                nameEn: 'Zambia',                    namePt: 'Zâmbia',                 flag: '🇿🇲', defaultTimezone: 'Africa/Lusaka' },
  { iso2: 'ZW', dialCode: '263', nameEs: 'Zimbabue',              nameEn: 'Zimbabwe',                  namePt: 'Zimbábue',               flag: '🇿🇼', defaultTimezone: 'Africa/Harare' },
];

/** Default country ISO2 for Sellio (Colombia). */
export const DEFAULT_COUNTRY = 'CO' as const;

/**
 * Countries in display order: CO, MX, BR, US, ES first, then the rest
 * alphabetically by nameEs. This is a direct reference to COUNTRIES since
 * the array is already in the correct order.
 */
export const countriesSorted: Country[] = COUNTRIES;

/**
 * Look up a country by its ISO 3166-1 alpha-2 code (case-insensitive).
 * Returns `undefined` if not found.
 */
export function getCountry(iso2: string): Country | undefined {
  const upper = iso2.toUpperCase();
  return COUNTRIES.find((c) => c.iso2 === upper);
}
